---
- name: Restart Server
  hosts: l13.233.89.186
  become: yes  # Run tasks with sudo (root) privileges

  tasks:
    - name: Restart the Server
      command: "reboot"
      async: 0
      poll: 0
